// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoSvrGameDB.proto

#ifndef PROTOBUF_ProtoSvrGameDB_2eproto__INCLUDED
#define PROTOBUF_ProtoSvrGameDB_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "ProtoSvrServerData.pb.h"
// @@protoc_insertion_point(includes)

namespace GameDBCmd {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ProtoSvrGameDB_2eproto();
void protobuf_AssignDesc_ProtoSvrGameDB_2eproto();
void protobuf_ShutdownFile_ProtoSvrGameDB_2eproto();

class RequestGetCharList;
class ResponseGetCharList;

enum SvrGameDBOpCode {
  GAMEDB_OP_GET_CHARLIST = 1
};
bool SvrGameDBOpCode_IsValid(int value);
const SvrGameDBOpCode SvrGameDBOpCode_MIN = GAMEDB_OP_GET_CHARLIST;
const SvrGameDBOpCode SvrGameDBOpCode_MAX = GAMEDB_OP_GET_CHARLIST;
const int SvrGameDBOpCode_ARRAYSIZE = SvrGameDBOpCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* SvrGameDBOpCode_descriptor();
inline const ::std::string& SvrGameDBOpCode_Name(SvrGameDBOpCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    SvrGameDBOpCode_descriptor(), value);
}
inline bool SvrGameDBOpCode_Parse(
    const ::std::string& name, SvrGameDBOpCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SvrGameDBOpCode>(
    SvrGameDBOpCode_descriptor(), name, value);
}
// ===================================================================

class RequestGetCharList : public ::google::protobuf::Message {
 public:
  RequestGetCharList();
  virtual ~RequestGetCharList();

  RequestGetCharList(const RequestGetCharList& from);

  inline RequestGetCharList& operator=(const RequestGetCharList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestGetCharList& default_instance();

  void Swap(RequestGetCharList* other);

  // implements Message ----------------------------------------------

  RequestGetCharList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestGetCharList& from);
  void MergeFrom(const RequestGetCharList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string account = 1;
  inline bool has_account() const;
  inline void clear_account();
  static const int kAccountFieldNumber = 1;
  inline const ::std::string& account() const;
  inline void set_account(const ::std::string& value);
  inline void set_account(const char* value);
  inline void set_account(const char* value, size_t size);
  inline ::std::string* mutable_account();
  inline ::std::string* release_account();
  inline void set_allocated_account(::std::string* account);

  // @@protoc_insertion_point(class_scope:GameDBCmd.RequestGetCharList)
 private:
  inline void set_has_account();
  inline void clear_has_account();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* account_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_ProtoSvrGameDB_2eproto();
  friend void protobuf_AssignDesc_ProtoSvrGameDB_2eproto();
  friend void protobuf_ShutdownFile_ProtoSvrGameDB_2eproto();

  void InitAsDefaultInstance();
  static RequestGetCharList* default_instance_;
};
// -------------------------------------------------------------------

class ResponseGetCharList : public ::google::protobuf::Message {
 public:
  ResponseGetCharList();
  virtual ~ResponseGetCharList();

  ResponseGetCharList(const ResponseGetCharList& from);

  inline ResponseGetCharList& operator=(const ResponseGetCharList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponseGetCharList& default_instance();

  void Swap(ResponseGetCharList* other);

  // implements Message ----------------------------------------------

  ResponseGetCharList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResponseGetCharList& from);
  void MergeFrom(const ResponseGetCharList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string account = 1;
  inline bool has_account() const;
  inline void clear_account();
  static const int kAccountFieldNumber = 1;
  inline const ::std::string& account() const;
  inline void set_account(const ::std::string& value);
  inline void set_account(const char* value);
  inline void set_account(const char* value, size_t size);
  inline ::std::string* mutable_account();
  inline ::std::string* release_account();
  inline void set_allocated_account(::std::string* account);

  // @@protoc_insertion_point(class_scope:GameDBCmd.ResponseGetCharList)
 private:
  inline void set_has_account();
  inline void clear_has_account();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* account_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_ProtoSvrGameDB_2eproto();
  friend void protobuf_AssignDesc_ProtoSvrGameDB_2eproto();
  friend void protobuf_ShutdownFile_ProtoSvrGameDB_2eproto();

  void InitAsDefaultInstance();
  static ResponseGetCharList* default_instance_;
};
// ===================================================================


// ===================================================================

// RequestGetCharList

// optional string account = 1;
inline bool RequestGetCharList::has_account() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestGetCharList::set_has_account() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestGetCharList::clear_has_account() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestGetCharList::clear_account() {
  if (account_ != &::google::protobuf::internal::kEmptyString) {
    account_->clear();
  }
  clear_has_account();
}
inline const ::std::string& RequestGetCharList::account() const {
  return *account_;
}
inline void RequestGetCharList::set_account(const ::std::string& value) {
  set_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    account_ = new ::std::string;
  }
  account_->assign(value);
}
inline void RequestGetCharList::set_account(const char* value) {
  set_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    account_ = new ::std::string;
  }
  account_->assign(value);
}
inline void RequestGetCharList::set_account(const char* value, size_t size) {
  set_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    account_ = new ::std::string;
  }
  account_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RequestGetCharList::mutable_account() {
  set_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    account_ = new ::std::string;
  }
  return account_;
}
inline ::std::string* RequestGetCharList::release_account() {
  clear_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = account_;
    account_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void RequestGetCharList::set_allocated_account(::std::string* account) {
  if (account_ != &::google::protobuf::internal::kEmptyString) {
    delete account_;
  }
  if (account) {
    set_has_account();
    account_ = account;
  } else {
    clear_has_account();
    account_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// ResponseGetCharList

// optional string account = 1;
inline bool ResponseGetCharList::has_account() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResponseGetCharList::set_has_account() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResponseGetCharList::clear_has_account() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResponseGetCharList::clear_account() {
  if (account_ != &::google::protobuf::internal::kEmptyString) {
    account_->clear();
  }
  clear_has_account();
}
inline const ::std::string& ResponseGetCharList::account() const {
  return *account_;
}
inline void ResponseGetCharList::set_account(const ::std::string& value) {
  set_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    account_ = new ::std::string;
  }
  account_->assign(value);
}
inline void ResponseGetCharList::set_account(const char* value) {
  set_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    account_ = new ::std::string;
  }
  account_->assign(value);
}
inline void ResponseGetCharList::set_account(const char* value, size_t size) {
  set_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    account_ = new ::std::string;
  }
  account_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ResponseGetCharList::mutable_account() {
  set_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    account_ = new ::std::string;
  }
  return account_;
}
inline ::std::string* ResponseGetCharList::release_account() {
  clear_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = account_;
    account_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ResponseGetCharList::set_allocated_account(::std::string* account) {
  if (account_ != &::google::protobuf::internal::kEmptyString) {
    delete account_;
  }
  if (account) {
    set_has_account();
    account_ = account;
  } else {
    clear_has_account();
    account_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace GameDBCmd

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::GameDBCmd::SvrGameDBOpCode>() {
  return ::GameDBCmd::SvrGameDBOpCode_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ProtoSvrGameDB_2eproto__INCLUDED
