// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMission.proto

#ifndef PROTOBUF_ProtoMission_2eproto__INCLUDED
#define PROTOBUF_ProtoMission_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "ProtoGameData.pb.h"
// @@protoc_insertion_point(includes)

namespace Protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ProtoMission_2eproto();
void protobuf_AssignDesc_ProtoMission_2eproto();
void protobuf_ShutdownFile_ProtoMission_2eproto();

class RequestAcceptMission;
class ResponseAcceptMission;
class RequestCompleteMission;
class ResponseCompleteMission;
class RequestCancelMission;
class ResponseCancelMission;
class RequestUpdateMission;
class NotifyUpdateMission;
class RequestChangeMission;
class NotifyChangeMission;

enum MissionOpCode {
  OP_MISSION_ACCEPT = 1,
  OP_MISSION_COMPETE = 2,
  OP_MISSION_CANCEL = 3,
  OP_MISSION_UPDATE = 4,
  OP_MISSION_CHANGE = 5
};
bool MissionOpCode_IsValid(int value);
const MissionOpCode MissionOpCode_MIN = OP_MISSION_ACCEPT;
const MissionOpCode MissionOpCode_MAX = OP_MISSION_CHANGE;
const int MissionOpCode_ARRAYSIZE = MissionOpCode_MAX + 1;

// ===================================================================

class RequestAcceptMission : public ::google::protobuf::MessageLite {
 public:
  RequestAcceptMission();
  virtual ~RequestAcceptMission();

  RequestAcceptMission(const RequestAcceptMission& from);

  inline RequestAcceptMission& operator=(const RequestAcceptMission& from) {
    CopyFrom(from);
    return *this;
  }

  static const RequestAcceptMission& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const RequestAcceptMission* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(RequestAcceptMission* other);

  // implements Message ----------------------------------------------

  RequestAcceptMission* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RequestAcceptMission& from);
  void MergeFrom(const RequestAcceptMission& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 mission_id = 1;
  inline bool has_mission_id() const;
  inline void clear_mission_id();
  static const int kMissionIdFieldNumber = 1;
  inline ::google::protobuf::int32 mission_id() const;
  inline void set_mission_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Protocol.RequestAcceptMission)
 private:
  inline void set_has_mission_id();
  inline void clear_has_mission_id();

  ::google::protobuf::int32 mission_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ProtoMission_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ProtoMission_2eproto();
  #endif
  friend void protobuf_AssignDesc_ProtoMission_2eproto();
  friend void protobuf_ShutdownFile_ProtoMission_2eproto();

  void InitAsDefaultInstance();
  static RequestAcceptMission* default_instance_;
};
// -------------------------------------------------------------------

class ResponseAcceptMission : public ::google::protobuf::MessageLite {
 public:
  ResponseAcceptMission();
  virtual ~ResponseAcceptMission();

  ResponseAcceptMission(const ResponseAcceptMission& from);

  inline ResponseAcceptMission& operator=(const ResponseAcceptMission& from) {
    CopyFrom(from);
    return *this;
  }

  static const ResponseAcceptMission& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const ResponseAcceptMission* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(ResponseAcceptMission* other);

  // implements Message ----------------------------------------------

  ResponseAcceptMission* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ResponseAcceptMission& from);
  void MergeFrom(const ResponseAcceptMission& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 mission_id = 1;
  inline bool has_mission_id() const;
  inline void clear_mission_id();
  static const int kMissionIdFieldNumber = 1;
  inline ::google::protobuf::int32 mission_id() const;
  inline void set_mission_id(::google::protobuf::int32 value);

  // optional int32 result = 2;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 2;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Protocol.ResponseAcceptMission)
 private:
  inline void set_has_mission_id();
  inline void clear_has_mission_id();
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::int32 mission_id_;
  ::google::protobuf::int32 result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ProtoMission_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ProtoMission_2eproto();
  #endif
  friend void protobuf_AssignDesc_ProtoMission_2eproto();
  friend void protobuf_ShutdownFile_ProtoMission_2eproto();

  void InitAsDefaultInstance();
  static ResponseAcceptMission* default_instance_;
};
// -------------------------------------------------------------------

class RequestCompleteMission : public ::google::protobuf::MessageLite {
 public:
  RequestCompleteMission();
  virtual ~RequestCompleteMission();

  RequestCompleteMission(const RequestCompleteMission& from);

  inline RequestCompleteMission& operator=(const RequestCompleteMission& from) {
    CopyFrom(from);
    return *this;
  }

  static const RequestCompleteMission& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const RequestCompleteMission* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(RequestCompleteMission* other);

  // implements Message ----------------------------------------------

  RequestCompleteMission* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RequestCompleteMission& from);
  void MergeFrom(const RequestCompleteMission& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 mission_id = 1;
  inline bool has_mission_id() const;
  inline void clear_mission_id();
  static const int kMissionIdFieldNumber = 1;
  inline ::google::protobuf::int32 mission_id() const;
  inline void set_mission_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Protocol.RequestCompleteMission)
 private:
  inline void set_has_mission_id();
  inline void clear_has_mission_id();

  ::google::protobuf::int32 mission_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ProtoMission_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ProtoMission_2eproto();
  #endif
  friend void protobuf_AssignDesc_ProtoMission_2eproto();
  friend void protobuf_ShutdownFile_ProtoMission_2eproto();

  void InitAsDefaultInstance();
  static RequestCompleteMission* default_instance_;
};
// -------------------------------------------------------------------

class ResponseCompleteMission : public ::google::protobuf::MessageLite {
 public:
  ResponseCompleteMission();
  virtual ~ResponseCompleteMission();

  ResponseCompleteMission(const ResponseCompleteMission& from);

  inline ResponseCompleteMission& operator=(const ResponseCompleteMission& from) {
    CopyFrom(from);
    return *this;
  }

  static const ResponseCompleteMission& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const ResponseCompleteMission* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(ResponseCompleteMission* other);

  // implements Message ----------------------------------------------

  ResponseCompleteMission* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ResponseCompleteMission& from);
  void MergeFrom(const ResponseCompleteMission& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 mission_id = 1;
  inline bool has_mission_id() const;
  inline void clear_mission_id();
  static const int kMissionIdFieldNumber = 1;
  inline ::google::protobuf::int32 mission_id() const;
  inline void set_mission_id(::google::protobuf::int32 value);

  // optional int32 result = 2;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 2;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Protocol.ResponseCompleteMission)
 private:
  inline void set_has_mission_id();
  inline void clear_has_mission_id();
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::int32 mission_id_;
  ::google::protobuf::int32 result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ProtoMission_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ProtoMission_2eproto();
  #endif
  friend void protobuf_AssignDesc_ProtoMission_2eproto();
  friend void protobuf_ShutdownFile_ProtoMission_2eproto();

  void InitAsDefaultInstance();
  static ResponseCompleteMission* default_instance_;
};
// -------------------------------------------------------------------

class RequestCancelMission : public ::google::protobuf::MessageLite {
 public:
  RequestCancelMission();
  virtual ~RequestCancelMission();

  RequestCancelMission(const RequestCancelMission& from);

  inline RequestCancelMission& operator=(const RequestCancelMission& from) {
    CopyFrom(from);
    return *this;
  }

  static const RequestCancelMission& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const RequestCancelMission* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(RequestCancelMission* other);

  // implements Message ----------------------------------------------

  RequestCancelMission* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RequestCancelMission& from);
  void MergeFrom(const RequestCancelMission& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 mission_id = 1;
  inline bool has_mission_id() const;
  inline void clear_mission_id();
  static const int kMissionIdFieldNumber = 1;
  inline ::google::protobuf::int32 mission_id() const;
  inline void set_mission_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Protocol.RequestCancelMission)
 private:
  inline void set_has_mission_id();
  inline void clear_has_mission_id();

  ::google::protobuf::int32 mission_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ProtoMission_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ProtoMission_2eproto();
  #endif
  friend void protobuf_AssignDesc_ProtoMission_2eproto();
  friend void protobuf_ShutdownFile_ProtoMission_2eproto();

  void InitAsDefaultInstance();
  static RequestCancelMission* default_instance_;
};
// -------------------------------------------------------------------

class ResponseCancelMission : public ::google::protobuf::MessageLite {
 public:
  ResponseCancelMission();
  virtual ~ResponseCancelMission();

  ResponseCancelMission(const ResponseCancelMission& from);

  inline ResponseCancelMission& operator=(const ResponseCancelMission& from) {
    CopyFrom(from);
    return *this;
  }

  static const ResponseCancelMission& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const ResponseCancelMission* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(ResponseCancelMission* other);

  // implements Message ----------------------------------------------

  ResponseCancelMission* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ResponseCancelMission& from);
  void MergeFrom(const ResponseCancelMission& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 mission_id = 1;
  inline bool has_mission_id() const;
  inline void clear_mission_id();
  static const int kMissionIdFieldNumber = 1;
  inline ::google::protobuf::int32 mission_id() const;
  inline void set_mission_id(::google::protobuf::int32 value);

  // optional int32 result = 2;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 2;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Protocol.ResponseCancelMission)
 private:
  inline void set_has_mission_id();
  inline void clear_has_mission_id();
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::int32 mission_id_;
  ::google::protobuf::int32 result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ProtoMission_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ProtoMission_2eproto();
  #endif
  friend void protobuf_AssignDesc_ProtoMission_2eproto();
  friend void protobuf_ShutdownFile_ProtoMission_2eproto();

  void InitAsDefaultInstance();
  static ResponseCancelMission* default_instance_;
};
// -------------------------------------------------------------------

class RequestUpdateMission : public ::google::protobuf::MessageLite {
 public:
  RequestUpdateMission();
  virtual ~RequestUpdateMission();

  RequestUpdateMission(const RequestUpdateMission& from);

  inline RequestUpdateMission& operator=(const RequestUpdateMission& from) {
    CopyFrom(from);
    return *this;
  }

  static const RequestUpdateMission& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const RequestUpdateMission* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(RequestUpdateMission* other);

  // implements Message ----------------------------------------------

  RequestUpdateMission* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RequestUpdateMission& from);
  void MergeFrom(const RequestUpdateMission& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 mission_id = 1;
  inline bool has_mission_id() const;
  inline void clear_mission_id();
  static const int kMissionIdFieldNumber = 1;
  inline ::google::protobuf::int32 mission_id() const;
  inline void set_mission_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Protocol.RequestUpdateMission)
 private:
  inline void set_has_mission_id();
  inline void clear_has_mission_id();

  ::google::protobuf::int32 mission_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ProtoMission_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ProtoMission_2eproto();
  #endif
  friend void protobuf_AssignDesc_ProtoMission_2eproto();
  friend void protobuf_ShutdownFile_ProtoMission_2eproto();

  void InitAsDefaultInstance();
  static RequestUpdateMission* default_instance_;
};
// -------------------------------------------------------------------

class NotifyUpdateMission : public ::google::protobuf::MessageLite {
 public:
  NotifyUpdateMission();
  virtual ~NotifyUpdateMission();

  NotifyUpdateMission(const NotifyUpdateMission& from);

  inline NotifyUpdateMission& operator=(const NotifyUpdateMission& from) {
    CopyFrom(from);
    return *this;
  }

  static const NotifyUpdateMission& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const NotifyUpdateMission* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(NotifyUpdateMission* other);

  // implements Message ----------------------------------------------

  NotifyUpdateMission* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const NotifyUpdateMission& from);
  void MergeFrom(const NotifyUpdateMission& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MissionData data = 1;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 1;
  inline const ::MissionData& data() const;
  inline ::MissionData* mutable_data();
  inline ::MissionData* release_data();
  inline void set_allocated_data(::MissionData* data);

  // @@protoc_insertion_point(class_scope:Protocol.NotifyUpdateMission)
 private:
  inline void set_has_data();
  inline void clear_has_data();

  ::MissionData* data_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ProtoMission_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ProtoMission_2eproto();
  #endif
  friend void protobuf_AssignDesc_ProtoMission_2eproto();
  friend void protobuf_ShutdownFile_ProtoMission_2eproto();

  void InitAsDefaultInstance();
  static NotifyUpdateMission* default_instance_;
};
// -------------------------------------------------------------------

class RequestChangeMission : public ::google::protobuf::MessageLite {
 public:
  RequestChangeMission();
  virtual ~RequestChangeMission();

  RequestChangeMission(const RequestChangeMission& from);

  inline RequestChangeMission& operator=(const RequestChangeMission& from) {
    CopyFrom(from);
    return *this;
  }

  static const RequestChangeMission& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const RequestChangeMission* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(RequestChangeMission* other);

  // implements Message ----------------------------------------------

  RequestChangeMission* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RequestChangeMission& from);
  void MergeFrom(const RequestChangeMission& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 mission_type = 1;
  inline bool has_mission_type() const;
  inline void clear_mission_type();
  static const int kMissionTypeFieldNumber = 1;
  inline ::google::protobuf::int32 mission_type() const;
  inline void set_mission_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Protocol.RequestChangeMission)
 private:
  inline void set_has_mission_type();
  inline void clear_has_mission_type();

  ::google::protobuf::int32 mission_type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ProtoMission_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ProtoMission_2eproto();
  #endif
  friend void protobuf_AssignDesc_ProtoMission_2eproto();
  friend void protobuf_ShutdownFile_ProtoMission_2eproto();

  void InitAsDefaultInstance();
  static RequestChangeMission* default_instance_;
};
// -------------------------------------------------------------------

class NotifyChangeMission : public ::google::protobuf::MessageLite {
 public:
  NotifyChangeMission();
  virtual ~NotifyChangeMission();

  NotifyChangeMission(const NotifyChangeMission& from);

  inline NotifyChangeMission& operator=(const NotifyChangeMission& from) {
    CopyFrom(from);
    return *this;
  }

  static const NotifyChangeMission& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const NotifyChangeMission* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(NotifyChangeMission* other);

  // implements Message ----------------------------------------------

  NotifyChangeMission* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const NotifyChangeMission& from);
  void MergeFrom(const NotifyChangeMission& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 require_money = 1;
  inline bool has_require_money() const;
  inline void clear_require_money();
  static const int kRequireMoneyFieldNumber = 1;
  inline ::google::protobuf::int32 require_money() const;
  inline void set_require_money(::google::protobuf::int32 value);

  // optional .MissionData data = 2;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 2;
  inline const ::MissionData& data() const;
  inline ::MissionData* mutable_data();
  inline ::MissionData* release_data();
  inline void set_allocated_data(::MissionData* data);

  // @@protoc_insertion_point(class_scope:Protocol.NotifyChangeMission)
 private:
  inline void set_has_require_money();
  inline void clear_has_require_money();
  inline void set_has_data();
  inline void clear_has_data();

  ::MissionData* data_;
  ::google::protobuf::int32 require_money_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ProtoMission_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ProtoMission_2eproto();
  #endif
  friend void protobuf_AssignDesc_ProtoMission_2eproto();
  friend void protobuf_ShutdownFile_ProtoMission_2eproto();

  void InitAsDefaultInstance();
  static NotifyChangeMission* default_instance_;
};
// ===================================================================


// ===================================================================

// RequestAcceptMission

// optional int32 mission_id = 1;
inline bool RequestAcceptMission::has_mission_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestAcceptMission::set_has_mission_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestAcceptMission::clear_has_mission_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestAcceptMission::clear_mission_id() {
  mission_id_ = 0;
  clear_has_mission_id();
}
inline ::google::protobuf::int32 RequestAcceptMission::mission_id() const {
  return mission_id_;
}
inline void RequestAcceptMission::set_mission_id(::google::protobuf::int32 value) {
  set_has_mission_id();
  mission_id_ = value;
}

// -------------------------------------------------------------------

// ResponseAcceptMission

// optional int32 mission_id = 1;
inline bool ResponseAcceptMission::has_mission_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResponseAcceptMission::set_has_mission_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResponseAcceptMission::clear_has_mission_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResponseAcceptMission::clear_mission_id() {
  mission_id_ = 0;
  clear_has_mission_id();
}
inline ::google::protobuf::int32 ResponseAcceptMission::mission_id() const {
  return mission_id_;
}
inline void ResponseAcceptMission::set_mission_id(::google::protobuf::int32 value) {
  set_has_mission_id();
  mission_id_ = value;
}

// optional int32 result = 2;
inline bool ResponseAcceptMission::has_result() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ResponseAcceptMission::set_has_result() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ResponseAcceptMission::clear_has_result() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ResponseAcceptMission::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 ResponseAcceptMission::result() const {
  return result_;
}
inline void ResponseAcceptMission::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// -------------------------------------------------------------------

// RequestCompleteMission

// optional int32 mission_id = 1;
inline bool RequestCompleteMission::has_mission_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestCompleteMission::set_has_mission_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestCompleteMission::clear_has_mission_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestCompleteMission::clear_mission_id() {
  mission_id_ = 0;
  clear_has_mission_id();
}
inline ::google::protobuf::int32 RequestCompleteMission::mission_id() const {
  return mission_id_;
}
inline void RequestCompleteMission::set_mission_id(::google::protobuf::int32 value) {
  set_has_mission_id();
  mission_id_ = value;
}

// -------------------------------------------------------------------

// ResponseCompleteMission

// optional int32 mission_id = 1;
inline bool ResponseCompleteMission::has_mission_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResponseCompleteMission::set_has_mission_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResponseCompleteMission::clear_has_mission_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResponseCompleteMission::clear_mission_id() {
  mission_id_ = 0;
  clear_has_mission_id();
}
inline ::google::protobuf::int32 ResponseCompleteMission::mission_id() const {
  return mission_id_;
}
inline void ResponseCompleteMission::set_mission_id(::google::protobuf::int32 value) {
  set_has_mission_id();
  mission_id_ = value;
}

// optional int32 result = 2;
inline bool ResponseCompleteMission::has_result() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ResponseCompleteMission::set_has_result() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ResponseCompleteMission::clear_has_result() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ResponseCompleteMission::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 ResponseCompleteMission::result() const {
  return result_;
}
inline void ResponseCompleteMission::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// -------------------------------------------------------------------

// RequestCancelMission

// optional int32 mission_id = 1;
inline bool RequestCancelMission::has_mission_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestCancelMission::set_has_mission_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestCancelMission::clear_has_mission_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestCancelMission::clear_mission_id() {
  mission_id_ = 0;
  clear_has_mission_id();
}
inline ::google::protobuf::int32 RequestCancelMission::mission_id() const {
  return mission_id_;
}
inline void RequestCancelMission::set_mission_id(::google::protobuf::int32 value) {
  set_has_mission_id();
  mission_id_ = value;
}

// -------------------------------------------------------------------

// ResponseCancelMission

// optional int32 mission_id = 1;
inline bool ResponseCancelMission::has_mission_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResponseCancelMission::set_has_mission_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResponseCancelMission::clear_has_mission_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResponseCancelMission::clear_mission_id() {
  mission_id_ = 0;
  clear_has_mission_id();
}
inline ::google::protobuf::int32 ResponseCancelMission::mission_id() const {
  return mission_id_;
}
inline void ResponseCancelMission::set_mission_id(::google::protobuf::int32 value) {
  set_has_mission_id();
  mission_id_ = value;
}

// optional int32 result = 2;
inline bool ResponseCancelMission::has_result() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ResponseCancelMission::set_has_result() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ResponseCancelMission::clear_has_result() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ResponseCancelMission::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 ResponseCancelMission::result() const {
  return result_;
}
inline void ResponseCancelMission::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// -------------------------------------------------------------------

// RequestUpdateMission

// optional int32 mission_id = 1;
inline bool RequestUpdateMission::has_mission_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestUpdateMission::set_has_mission_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestUpdateMission::clear_has_mission_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestUpdateMission::clear_mission_id() {
  mission_id_ = 0;
  clear_has_mission_id();
}
inline ::google::protobuf::int32 RequestUpdateMission::mission_id() const {
  return mission_id_;
}
inline void RequestUpdateMission::set_mission_id(::google::protobuf::int32 value) {
  set_has_mission_id();
  mission_id_ = value;
}

// -------------------------------------------------------------------

// NotifyUpdateMission

// optional .MissionData data = 1;
inline bool NotifyUpdateMission::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NotifyUpdateMission::set_has_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NotifyUpdateMission::clear_has_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NotifyUpdateMission::clear_data() {
  if (data_ != NULL) data_->::MissionData::Clear();
  clear_has_data();
}
inline const ::MissionData& NotifyUpdateMission::data() const {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return data_ != NULL ? *data_ : *default_instance().data_;
#else
  return data_ != NULL ? *data_ : *default_instance_->data_;
#endif
}
inline ::MissionData* NotifyUpdateMission::mutable_data() {
  set_has_data();
  if (data_ == NULL) data_ = new ::MissionData;
  return data_;
}
inline ::MissionData* NotifyUpdateMission::release_data() {
  clear_has_data();
  ::MissionData* temp = data_;
  data_ = NULL;
  return temp;
}
inline void NotifyUpdateMission::set_allocated_data(::MissionData* data) {
  delete data_;
  data_ = data;
  if (data) {
    set_has_data();
  } else {
    clear_has_data();
  }
}

// -------------------------------------------------------------------

// RequestChangeMission

// optional int32 mission_type = 1;
inline bool RequestChangeMission::has_mission_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestChangeMission::set_has_mission_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestChangeMission::clear_has_mission_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestChangeMission::clear_mission_type() {
  mission_type_ = 0;
  clear_has_mission_type();
}
inline ::google::protobuf::int32 RequestChangeMission::mission_type() const {
  return mission_type_;
}
inline void RequestChangeMission::set_mission_type(::google::protobuf::int32 value) {
  set_has_mission_type();
  mission_type_ = value;
}

// -------------------------------------------------------------------

// NotifyChangeMission

// optional int32 require_money = 1;
inline bool NotifyChangeMission::has_require_money() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NotifyChangeMission::set_has_require_money() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NotifyChangeMission::clear_has_require_money() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NotifyChangeMission::clear_require_money() {
  require_money_ = 0;
  clear_has_require_money();
}
inline ::google::protobuf::int32 NotifyChangeMission::require_money() const {
  return require_money_;
}
inline void NotifyChangeMission::set_require_money(::google::protobuf::int32 value) {
  set_has_require_money();
  require_money_ = value;
}

// optional .MissionData data = 2;
inline bool NotifyChangeMission::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NotifyChangeMission::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NotifyChangeMission::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NotifyChangeMission::clear_data() {
  if (data_ != NULL) data_->::MissionData::Clear();
  clear_has_data();
}
inline const ::MissionData& NotifyChangeMission::data() const {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return data_ != NULL ? *data_ : *default_instance().data_;
#else
  return data_ != NULL ? *data_ : *default_instance_->data_;
#endif
}
inline ::MissionData* NotifyChangeMission::mutable_data() {
  set_has_data();
  if (data_ == NULL) data_ = new ::MissionData;
  return data_;
}
inline ::MissionData* NotifyChangeMission::release_data() {
  clear_has_data();
  ::MissionData* temp = data_;
  data_ = NULL;
  return temp;
}
inline void NotifyChangeMission::set_allocated_data(::MissionData* data) {
  delete data_;
  data_ = data;
  if (data) {
    set_has_data();
  } else {
    clear_has_data();
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ProtoMission_2eproto__INCLUDED
