// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoOnlineRewards.proto

#ifndef PROTOBUF_ProtoOnlineRewards_2eproto__INCLUDED
#define PROTOBUF_ProtoOnlineRewards_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "ProtoGameData.pb.h"
// @@protoc_insertion_point(includes)

namespace Protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ProtoOnlineRewards_2eproto();
void protobuf_AssignDesc_ProtoOnlineRewards_2eproto();
void protobuf_ShutdownFile_ProtoOnlineRewards_2eproto();

class NotifyOnlineRewardsUpdateInfo;
class RequestOnlineRewardsTakeAward;

enum OnlineRewardsOpCode {
  OP_ONLINE_REWARDS_UPDATE_INFO = 1,
  OP_ONLINE_REWARDS_TAKE_AWARD = 2
};
bool OnlineRewardsOpCode_IsValid(int value);
const OnlineRewardsOpCode OnlineRewardsOpCode_MIN = OP_ONLINE_REWARDS_UPDATE_INFO;
const OnlineRewardsOpCode OnlineRewardsOpCode_MAX = OP_ONLINE_REWARDS_TAKE_AWARD;
const int OnlineRewardsOpCode_ARRAYSIZE = OnlineRewardsOpCode_MAX + 1;

// ===================================================================

class NotifyOnlineRewardsUpdateInfo : public ::google::protobuf::MessageLite {
 public:
  NotifyOnlineRewardsUpdateInfo();
  virtual ~NotifyOnlineRewardsUpdateInfo();

  NotifyOnlineRewardsUpdateInfo(const NotifyOnlineRewardsUpdateInfo& from);

  inline NotifyOnlineRewardsUpdateInfo& operator=(const NotifyOnlineRewardsUpdateInfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const NotifyOnlineRewardsUpdateInfo& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const NotifyOnlineRewardsUpdateInfo* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(NotifyOnlineRewardsUpdateInfo* other);

  // implements Message ----------------------------------------------

  NotifyOnlineRewardsUpdateInfo* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const NotifyOnlineRewardsUpdateInfo& from);
  void MergeFrom(const NotifyOnlineRewardsUpdateInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .OnlineRewardsData data = 1;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 1;
  inline const ::OnlineRewardsData& data() const;
  inline ::OnlineRewardsData* mutable_data();
  inline ::OnlineRewardsData* release_data();
  inline void set_allocated_data(::OnlineRewardsData* data);

  // @@protoc_insertion_point(class_scope:Protocol.NotifyOnlineRewardsUpdateInfo)
 private:
  inline void set_has_data();
  inline void clear_has_data();

  ::OnlineRewardsData* data_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ProtoOnlineRewards_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ProtoOnlineRewards_2eproto();
  #endif
  friend void protobuf_AssignDesc_ProtoOnlineRewards_2eproto();
  friend void protobuf_ShutdownFile_ProtoOnlineRewards_2eproto();

  void InitAsDefaultInstance();
  static NotifyOnlineRewardsUpdateInfo* default_instance_;
};
// -------------------------------------------------------------------

class RequestOnlineRewardsTakeAward : public ::google::protobuf::MessageLite {
 public:
  RequestOnlineRewardsTakeAward();
  virtual ~RequestOnlineRewardsTakeAward();

  RequestOnlineRewardsTakeAward(const RequestOnlineRewardsTakeAward& from);

  inline RequestOnlineRewardsTakeAward& operator=(const RequestOnlineRewardsTakeAward& from) {
    CopyFrom(from);
    return *this;
  }

  static const RequestOnlineRewardsTakeAward& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const RequestOnlineRewardsTakeAward* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(RequestOnlineRewardsTakeAward* other);

  // implements Message ----------------------------------------------

  RequestOnlineRewardsTakeAward* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RequestOnlineRewardsTakeAward& from);
  void MergeFrom(const RequestOnlineRewardsTakeAward& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Protocol.RequestOnlineRewardsTakeAward)
 private:
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::int32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ProtoOnlineRewards_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ProtoOnlineRewards_2eproto();
  #endif
  friend void protobuf_AssignDesc_ProtoOnlineRewards_2eproto();
  friend void protobuf_ShutdownFile_ProtoOnlineRewards_2eproto();

  void InitAsDefaultInstance();
  static RequestOnlineRewardsTakeAward* default_instance_;
};
// ===================================================================


// ===================================================================

// NotifyOnlineRewardsUpdateInfo

// optional .OnlineRewardsData data = 1;
inline bool NotifyOnlineRewardsUpdateInfo::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NotifyOnlineRewardsUpdateInfo::set_has_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NotifyOnlineRewardsUpdateInfo::clear_has_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NotifyOnlineRewardsUpdateInfo::clear_data() {
  if (data_ != NULL) data_->::OnlineRewardsData::Clear();
  clear_has_data();
}
inline const ::OnlineRewardsData& NotifyOnlineRewardsUpdateInfo::data() const {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return data_ != NULL ? *data_ : *default_instance().data_;
#else
  return data_ != NULL ? *data_ : *default_instance_->data_;
#endif
}
inline ::OnlineRewardsData* NotifyOnlineRewardsUpdateInfo::mutable_data() {
  set_has_data();
  if (data_ == NULL) data_ = new ::OnlineRewardsData;
  return data_;
}
inline ::OnlineRewardsData* NotifyOnlineRewardsUpdateInfo::release_data() {
  clear_has_data();
  ::OnlineRewardsData* temp = data_;
  data_ = NULL;
  return temp;
}
inline void NotifyOnlineRewardsUpdateInfo::set_allocated_data(::OnlineRewardsData* data) {
  delete data_;
  data_ = data;
  if (data) {
    set_has_data();
  } else {
    clear_has_data();
  }
}

// -------------------------------------------------------------------

// RequestOnlineRewardsTakeAward

// optional int32 id = 1;
inline bool RequestOnlineRewardsTakeAward::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestOnlineRewardsTakeAward::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestOnlineRewardsTakeAward::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestOnlineRewardsTakeAward::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 RequestOnlineRewardsTakeAward::id() const {
  return id_;
}
inline void RequestOnlineRewardsTakeAward::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ProtoOnlineRewards_2eproto__INCLUDED
